"""Data constants for conjugation service - mappings and descriptions."""

# Mapping from Auxiliary enum to human-readable descriptions
AUXILIARY_DESCRIPTIONS: dict[str, tuple[str, str]] = {
    "POTENTIAL": ("potential", "can/able to"),
    "MASU": ("polite", "polite form"),
    "NAI": ("negative", "not"),
    "TAI": ("desiderative", "want to"),
    "TAGARU": ("desiderative", "seems to want"),
    "HOSHII": ("desiderative", "want someone to"),
    "RASHII": ("evidential", "apparently"),
    "SOUDA_HEARSAY": ("hearsay", "I heard that"),
    "SOUDA_CONJECTURE": ("conjecture", "looks like"),
    "SERU_SASERU": ("causative", "make/let do"),
    "SHORTENED_CAUSATIVE": ("causative", "make/let do"),
    "RERU_RARERU": ("passive/potential", "is done/can do"),
    "CAUSATIVE_PASSIVE": ("causative-passive", "is made to do"),
    "SHORTENED_CAUSATIVE_PASSIVE": ("causative-passive", "is made to do"),
    "AGERU": ("benefactive", "do for someone"),
    "SASHIAGERU": ("benefactive-humble", "humbly do for"),
    "YARU": ("benefactive-casual", "do for (casual)"),
    "MORAU": ("receptive", "have done for me"),
    "ITADAKU": ("receptive-humble", "humbly receive"),
    "KURERU": ("benefactive-to-me", "do for me"),
    "KUDASARU": ("benefactive-humble", "kindly do for me"),
    "TE_IRU": ("progressive/resultative", "is doing/has done"),
    "TE_ARU": ("resultative", "has been done"),
    "MIRU": ("tentative", "try doing"),
    "IKU": ("directional", "go on doing"),
    "KURU": ("directional", "come to do"),
    "OKU": ("preparatory", "do in advance"),
    "SHIMAU": ("completive", "end up doing"),
    "TE_ORU": ("progressive-humble", "is doing (humble)"),
    # New auxiliaries
    "SUGIRU": ("excessive", "too much"),
    "YASUI": ("ease", "easy to"),
    "NIKUI": ("difficulty", "hard to"),
    "HAJIMERU": ("inchoative", "start doing"),
    "OWARU": ("terminative", "finish doing"),
    "TSUZUKERU": ("continuative", "continue doing"),
    "DASU": ("sudden", "burst into"),
    "GARU": ("appearance", "seems to want"),
    "SOU_APPEARANCE": ("appearance", "looks like"),
    "NASAI": ("imperative", "command (polite)"),
}

# Mapping from Conjugation enum to descriptions
CONJUGATION_DESCRIPTIONS: dict[str, tuple[str, str]] = {
    "NEGATIVE": ("negative", "not"),
    "CONJUNCTIVE": ("masu-stem", "connective"),
    "DICTIONARY": ("dictionary", "plain present"),
    "CONDITIONAL": ("conditional", "if/when"),
    "IMPERATIVE": ("imperative", "command"),
    "VOLITIONAL": ("volitional", "let's/will"),
    "TE": ("te-form", "and/request"),
    "TA": ("past", "did"),
    "TARA": ("conditional-past", "if/when"),
    "TARI": ("representative", "things like"),
    "ZU": ("classical-negative", "without"),
    "NU": ("classical-negative", "not"),
}

# Grammar explanations for particles, auxiliaries, pronouns
GRAMMAR_MAP = {
    # Particles
    "は": "topic marker",
    "が": "subject marker",
    "を": "object marker",
    "に": "direction/time/target",
    "で": "location/means",
    "の": "possessive/of",
    "と": "and/with/quote",
    "も": "also/too",
    "から": "from/because",
    "まで": "until/to",
    "へ": "toward",
    "より": "than/from",
    "か": "question/or",
    "ね": "isn't it?",
    "よ": "emphasis",
    "な": "don't!/attributive",
    "わ": "feminine emphasis",
    "ぞ": "strong emphasis",
    "さ": "filler/emphasis",
    "て": "connection/request",
    "けど": "but/although",
    "けれど": "but/although",
    "けれども": "but/although",
    "のに": "despite/although",
    "ので": "because/so",
    "たり": "doing things like",
    "ながら": "while doing",
    "ばかり": "only/just",
    "だけ": "only/just",
    "しか": "only (with neg)",
    "ほど": "extent/degree",
    "くらい": "about/approximately",
    "など": "etc./and so on",
    "こそ": "emphasis (this very)",
    "さえ": "even",
    "すら": "even",
    "でも": "but/even",
    "とも": "both/even if",
    "やら": "or/what with",
    "なら": "if/as for",
    "たら": "if/when",
    "ば": "if/when",
    "って": "quotation (casual)",
    # Auxiliaries
    "ます": "polite form",
    "です": "copula (polite)",
    "だ": "copula (plain)",
    "た": "past tense",
    "ない": "negation",
    "ぬ": "negation (archaic)",
    "れる": "passive/potential",
    "られる": "passive/potential",
    "せる": "causative",
    "させる": "causative",
    "たい": "want to",
    "たがる": "seems to want",
    "そう": "seems like",
    "よう": "manner/let's",
    "らしい": "seems/apparently",
    "べき": "should",
    "はず": "expected to",
    "まい": "won't/probably not",
    # Copula conjugation forms
    "だろう": "copula (plain) + conjectural: probably",
    "でしょう": "copula (polite) + conjectural: probably",
    "である": "copula (formal)",
    "であります": "copula (formal) + polite",
    "ではある": "copula (formal) + contrastive",
    "ではない": "copula + negative: is not",
    "じゃない": "copula + negative (casual): isn't",
    "ではありません": "copula + negative + polite: is not",
    "じゃありません": "copula + negative + polite (casual): isn't",
    "だった": "copula (plain) + past: was",
    "でした": "copula (polite) + past: was",
    "ではなかった": "copula + negative + past: wasn't",
    "じゃなかった": "copula + negative + past (casual): wasn't",
    "ではありませんでした": "copula + negative + polite + past: wasn't",
    # Pronouns
    "私": "I/me",
    "僕": "I (male)",
    "俺": "I (rough male)",
    "あなた": "you",
    "君": "you (familiar)",
    "彼": "he/him",
    "彼女": "she/her",
    "これ": "this",
    "それ": "that",
    "あれ": "that (over there)",
    "ここ": "here",
    "そこ": "there",
    "あそこ": "over there",
    "誰": "who",
    "何": "what",
    "どこ": "where",
    "いつ": "when",
    "どう": "how",
    "なぜ": "why",
    "どれ": "which",
}

# POS mapping to English
POS_MAP = {
    "名詞": "Noun",
    "動詞": "Verb",
    "形容詞": "i-Adj",
    "形状詞": "na-Adj",
    "副詞": "Adverb",
    "助詞": "Particle",
    "助動詞": "Aux",
    "接続詞": "Conj",
    "連体詞": "Adnominal",
    "感動詞": "Interj",
    "接頭辞": "Prefix",
    "接尾辞": "Suffix",
    "代名詞": "Pronoun",
    "補助記号": "Punct",
    "記号": "Symbol",
}

# POS whitelist for simple analysis
POS_WHITELIST = frozenset({"名詞", "動詞", "形容詞", "形状詞"})

# POS to skip
SKIP_POS = frozenset({"補助記号", "記号", "空白"})
